### ISSUE TITLE
Vite 4.3.9 compatibility

### ISSUE THREAD

**Issue by jrson83** [bienzaaron/vite-plugin-inline-source#255]
Using Vite@4.3.9 with following config, I get TypeRrror.

![Screenshot 2023-06-28 144934](https://github.com/bienzaaron/vite-plugin-inline-source/assets/45284565/cc76221e-01d3-47fb-9dee-9b70146e8df3)

```ts
import preact from '@preact/preset-vite'
import { defineConfig } from 'vite'
import inlineSource from 'vite-plugin-inline-source'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    preact(),
    inlineSource(),
  ],
  server: {
    host: true,
  },
})
```

Providing an option:

```ts
inlineSource({
  replaceTags: ['style'],
}),
```

Throws another error, when running `pnpm dev`:

```sh
failed to load config from D:\___projects\tests\comps\vite.config.ts
error when starting dev server:
TypeError: inlineSource is not a function
    at file:///D:/___projects/tests/comps/vite.config.ts.timestamp-1687956498822-c3b6e3b189067.mjs:22:5
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by bienzaaron** [comment]
Sorry I am just now seeing this :/ the typings on `options` need adjusted slightly for that first error, and the second one probably just needed `inlineSource.default()` due to the way `tsc` builds things for cjs/esm support.

#274 / `v2.3.0` should fix both - added a different build process which produces separate cjs/esm builds and fixed that options type.
